apiVersion: dispatcher.taskstation.io/v1alpha1
kind: Task
metadata:
  labels:
    app.kubernetes.io/name: task
    app.kubernetes.io/instance: task-sample
    app.kubernetes.io/part-of: taskstation
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: taskstation
  name: task-sample
spec:
  # TODO(user): Add fields here
